name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11']

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      # https://github.com/actions/setup-python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # https://github.com/actions/setup-node
      - name: Setup Node for datadog-ci command
        uses: actions/setup-node@v3

      - name: Install datadog-ci
        run: npm install -g @datadog/datadog-ci
        
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
          pip install -e .

      - name: Test with pytest
        env: 
          DD_CIVISIBILITY_AGENTLESS_ENABLED: true
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DATADOG_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_SITE: datadoghq.com
          DD_ENV: pre-ci
          DD_SERVICE: python-ci-testing-template
        run: datadog-ci tag --level pipeline --tags team:bestpod && pytest --ddtrace
      
      # https://github.com/marketplace/actions/datadog-synthetics-ci
      - name: Run Datadog Synthetic tests
        uses: DataDog/synthetics-ci-github-action@v0.18.0
        with:
          api_key: ${{secrets.DD_API_KEY}}
          app_key: ${{secrets.DD_APP_KEY}}
          public_ids: ${{secrets.DD_SYN_TEST}}
